# Generated by Django 2.2.21 on 2021-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Imovel',
                'verbose_name_plural': 'Imoveis',
                'ordering': ['id', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Imobiliaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imovel', models.ManyToManyField(related_name='Imoveis', to='core.Imovel')),
            ],
            options={
                'verbose_name': 'Imobiliaria',
                'verbose_name_plural': 'Imobiliarias',
                'ordering': ['id', 'nome'],
            },
        ),
    ]
