# Generated by Django 2.2.21 on 2021-05-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imobiliaria',
            name='imovel',
        ),
        migrations.AddField(
            model_name='imovel',
            name='imobiliaria',
            field=models.ManyToManyField(related_name='Imobiliarias', to='core.Imobiliaria'),
        ),
    ]
