# Generated by Django 2.2.21 on 2021-05-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['id'], 'verbose_name': 'Endereco', 'verbose_name_plural': 'Enderecos'},
        ),
        migrations.AlterModelOptions(
            name='imobiliaria',
            options={'ordering': ['id', 'nome'], 'verbose_name': 'Imobiliaria', 'verbose_name_plural': 'Imobiliarias'},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['id', 'nome'], 'verbose_name': 'Imovel', 'verbose_name_plural': 'Imoveis'},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['id', 'categoria'], 'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tipo',
            name='slug',
        ),
    ]
