# Generated by Django 2.2.21 on 2021-05-06 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210506_0205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='status',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='finalidade',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='status',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
