# Generated by Django 2.2.21 on 2021-05-06 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210506_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imobiliaria',
            name='imovel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Imovel'),
        ),
    ]
