# Generated by Django 2.2.21 on 2021-05-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': ['Endereco'], 'verbose_name_plural': 'Enderecos'},
        ),
        migrations.AddField(
            model_name='imovel',
            name='endereco',
            field=models.ManyToManyField(related_name='Endereco', to='core.Endereco'),
        ),
    ]
