# Generated by Django 2.2.21 on 2021-05-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210507_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'Endereco', 'verbose_name_plural': 'Enderecos'},
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='endereco',
            field=models.ManyToManyField(related_name='imobiliaria_endereco', to='core.Endereco'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.ManyToManyField(related_name='imovel_endereco', to='core.Endereco'),
        ),
    ]
