# Generated by Django 2.2.21 on 2021-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210507_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='imobiliaria',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
