# Generated by Django 2.2.21 on 2021-05-08 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imovel_finalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento')], max_length=20),
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Imovel')),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
    ]
