# Generated by Django 2.2.21 on 2021-05-09 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210509_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='local',
        ),
        migrations.RemoveField(
            model_name='local',
            name='nome',
        ),
        migrations.AddField(
            model_name='local',
            name='imovel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='core.Imovel'),
            preserve_default=False,
        ),
    ]
