# Generated by Django 2.2.21 on 2021-05-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210509_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='imovel',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='imobiliaria',
            name='status',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='imobiliaria',
        ),
        migrations.AddField(
            model_name='imobiliaria',
            name='endereço',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
    ]
