# Generated by Django 2.2.21 on 2021-05-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210509_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
