# Generated by Django 2.2.21 on 2021-05-09 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_imovel_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='imobiliaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imobiliaria', to='core.Imobiliaria'),
            preserve_default=False,
        ),
    ]
