# Generated by Django 2.2.21 on 2021-05-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_imovel_imobiliaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imobiliaria',
            options={'ordering': ['nome'], 'verbose_name': 'Imobiliaria', 'verbose_name_plural': 'Imobiliarias'},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['nome'], 'verbose_name': 'Imovel', 'verbose_name_plural': 'Imoveis'},
        ),
        migrations.AddField(
            model_name='imovel',
            name='caracteristicas',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='descricao',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imobiliaria',
            name='endereço',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imobiliaria',
            field=models.ForeignKey(on_delete=models.SET('1'), related_name='imobiliaria', to='core.Imobiliaria'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
